### PR TITLE
Winter refactoring

### PR DESCRIPTION
**Pull request by jbbarth**
See botify-labs/simpleflow#76. WIP, do not merge.

I'm just opening the PR now so that Travis builds this along the way.

### CODE REVIEW

**Comment by jbbarth** [comment]
Ready to merge if you want to review, ping @ybastide @ampelmann @benjastudio 

Mostly cosmetic changes except the addition of a `Decider.poll_for_task()` method, that returns a response object containing workflow execution informations. See botify-labs/simpleflow#76 for why it's useful.

I'll open a new issue here so we consider merging the 2 projects for easier management.

**Comment by ybastide** [comment]
Perhaps a flake8 pass? :-) (with
```
[flake8]
max-line-length = 120
```
in `setup.cfg`, obviously)

Other than that: :+1:

**Comment by jbbarth** [comment]
Yes for flake8, no pb! For now I don't run flake8 on this project but it would be a good idea, obviously. I'll add that and merge this, thanks!!

**Comment by ampelmann** [comment]
:+1:

**Comment by benjastudio** [comment]
:+1:

**Pull request merged**
